// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuyContent: typeof import('./src/components/BuyContent/index.vue')['default']
    BuyFrame: typeof import('./src/components/BuyFrame/index.vue')['default']
    OrderDetail: typeof import('./src/components/OrderDetail/index.vue')['default']
    OrderItem: typeof import('./src/components/OrderItem/index.vue')['default']
    SwiperBox: typeof import('./src/components/SwiperBox/index.vue')['default']
  }
}
